project:
  title: "methods-meetup"
  type: website

format:
  revealjs:
    theme: [default, theme.scss]
    date-format: long
    logo: bhhi-logo.png
    code-overflow: wrap
    code-line-numbers: false
    highlight-style: a11y
    knitr:
      opts_chunk:
        dev: ragg_png
        dpi: 144


